### ISSUE TITLE
Translation Readme to Portuguese-BR

### ISSUE THREAD

**Issue by tiagobpires** [harshithq/ColorGame#10]
Hi @harshithq ! I would like to contribute translating the readme to Portuguese-BR.  Would it be interesting to contibute as this way? 
If yes, please tell me which readme to use.

**Comment by harshithq** [comment]
That is supportive @tiagobpires , feel free to change any of the readme files. Just send a PR and I will merge it

**Comment by tiagobpires** [comment]
Thank you! I already sended you a PR for this
